import webdev from './webdev.jpg'
import mern from './mern.avif'
import uiux from './uiux.png'
import app from './app.png'
import mar from './mar.png'
import iot from './pics/iott.webp'
import block from './pics/block.png'
import c from './pics/c.png'
import cc from './pics/cc.webp'
import cloud from './pics/cloud.jpeg'
import django from './pics/django.jpg'
import flut from './pics/flut.webp'
import java from './pics/java.png'
import ml from './pics/ml.jpg'
import node from './pics/node.png'
import react from './pics/react.png'
import py from './pics/python.png'

const courseDetails = {
  'html-css': {
    title: 'HTML & CSS',
    description: 'Learn the basics of web design with HTML and CSS.',
    duration: '3 months',
    cost: '$200',
    classes: 'Weekends (Sat & Sun)',
    certification: 'Certificate of Completion',
    projects: '2 mini projects and 1 major project',
    topics: [
      'Introduction to HTML & CSS ',
      'HTML5 Semantic Elements',
      'CSS Grid and Flexbox',
      'Responsive Design',
      'CSS Animations',
      'Introduction to HTML & CSS ',
      'HTML5 Semantic Elements',
      'CSS Grid and Flexbox',
      'Responsive Design',
      'CSS Animations',
    ],
    image: webdev,
  },
  mern: {
    title: 'MERN Stack Development',
    description: 'Master MongoDB, Express, React, and Node.js for full-stack web development.',
    duration: '6 months',
    cost: '$500',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Professional MERN Developer Certification',
    projects: '3 full-stack projects',
    topics: [
      'React Fundamentals',
      'Building REST APIs with Express.js',
      'MongoDB Database Operations',
      'User Authentication and Authorization',
      'Deployment with Docker',
    ],
    image: mern,
  },
  'ui-ux': {
    title: 'UI/UX Design',
    description: 'Learn to create user-friendly designs with modern tools.',
    duration: '4 months',
    cost: '$300',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Professional MERN Developer Certification',
    projects: '3 full-stack projects',
    topics: [
      'React Fundamentals',
      'Building REST APIs with Express.js',
      'MongoDB Database Operations',
      'User Authentication and Authorization',
      'Deployment with Docker',
    ],
    image: uiux,
  },
  'app-dev': {
    title: 'App Development',
    description: 'Learn to build native Android and iOS applications.',
    duration: '5 months',
    cost: '$400',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Professional MERN Developer Certification',
    projects: '3 full-stack projects',
    topics: [
      'React Fundamentals',
      'Building REST APIs with Express.js',
      'MongoDB Database Operations',
      'User Authentication and Authorization',
      'Deployment with Docker',
    ],
    image:app,
  },
  'digital-marketing': {
    title: 'Digital Marketing',
    description: 'Master online marketing strategies to grow businesses.',
    duration: '2 months',
    cost: '$150',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Professional MERN Developer Certification',
    projects: '3 full-stack projects',
    topics: [
      'React Fundamentals',
      'Building REST APIs with Express.js',
      'MongoDB Database Operations',
      'User Authentication and Authorization',
      'Deployment with Docker',
    ],
    image:mar,
  },
  'python-programming': {
    title: 'Python Programming',
    description: 'Master Python from basics to advanced concepts.',
    duration: '5 months',
    cost: '$300',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Python Developer Certificate',
    projects: '6 real-world projects',
    topics: [
      'Introduction to Python',
      'Variables, Data Types, and Operators',
      'Control Structures and Loops',
      'Functions and Modules',
      'Object-Oriented Programming',
      'Data Structures and Algorithms',
      'Working with Libraries (NumPy, Pandas)',
      'File Handling and Error Management',
      'Web Scraping with Python',
      'Building GUI Applications',
    ],
    image: py,
  },
  'cloud-computing': {
    title: 'Cloud Computing',
    description: 'Master cloud platforms like AWS and Azure.',
    duration: '4 months',
    cost: '$350',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Cloud Computing Specialist Certificate',
    projects: '4 cloud deployment projects',
    topics: [
      'Introduction to Cloud Computing',
      'Understanding AWS and Azure Platforms',
      'Virtual Machines and Storage Solutions',
      'Cloud Networking Basics',
      'Cloud Security Best Practices',
      'Serverless Computing and Function as a Service',
      'Deploying Applications on AWS',
      'Managing Resources in Azure',
      'Introduction to Kubernetes and Docker',
      'Cloud Monitoring and Maintenance',
    ],
    image: cloud,
  },
  'blockchain': {
    title: 'Blockchain Development',
    description: 'Learn blockchain technology and smart contracts.',
    duration: '6 months',
    cost: '$500',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Blockchain Developer Certificate',
    projects: '5 blockchain-based projects',
    topics: [
      'Introduction to Blockchain Technology',
      'Cryptography Basics',
      'Decentralized Applications (DApps)',
      'Smart Contracts with Solidity',
      'Blockchain Architecture and Nodes',
      'Ethereum and Other Platforms',
      'Consensus Mechanisms (PoW, PoS)',
      'NFT and Token Standards',
      'Real-world Applications of Blockchain',
      'Blockchain Deployment and Maintenance',
    ],
    image: block,
  },
  'machine-learning': {
  title: 'Machine Learning',
  description: 'Master machine learning algorithms and models for data analysis and prediction.',
  duration: '6 months',
  cost: '$450',
  classes: 'Weekdays (Mon to Fri)',
  certification: 'Machine Learning Specialist Certificate',
  projects: '5 machine learning projects',
  topics: [
    'Introduction to Machine Learning',
    'Supervised Learning Algorithms',
    'Unsupervised Learning Algorithms',
    'Data Preprocessing and Feature Engineering',
    'Model Evaluation and Validation',
    'Neural Networks and Deep Learning',
    'Natural Language Processing (NLP)',
    'Reinforcement Learning',
    'Dimensionality Reduction',
    'Machine Learning with Python (Scikit-learn, TensorFlow)',
  ],
  image: ml,
}
,
  'java': {
    title: 'Java Programming',
    description: 'Learn Java for software development and object-oriented programming.',
    duration: '3 months',
    cost: '$200',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Java Developer Certificate',
    projects: '3 software development projects',
    topics: [
      'Introduction to Java',
      'Variables, Data Types, and Operators',
      'Control Statements and Loops',
      'Object-Oriented Programming',
      'Exception Handling',
      'File I/O in Java',
      'Java Collections Framework',
      'Multithreading and Concurrency',
      'JDBC and Database Connectivity',
      'Developing Applications with JavaFX',
    ],
    image: java,
  },
  'c-programming': {
    title: 'C Programming',
    description: 'Master the fundamentals of C programming for system-level development.',
    duration: '2 months',
    cost: '$150',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'C Programmer Certificate',
    projects: '2 system-level projects',
    topics: [
      'Introduction to C Programming',
      'Data Types and Variables',
      'Control Flow and Loops',
      'Functions and Recursion',
      'Pointers and Memory Management',
      'Arrays and Strings',
      'Structures and Unions',
      'File Handling in C',
      'Dynamic Memory Allocation',
      'Basic Data Structures in C',
    ],
    image: c,
  },
  'cpp-programming': {
    title: 'C++ Programming',
    description: 'Build advanced applications with object-oriented features in C++.',
    duration: '3 months',
    cost: '$200',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'C++ Developer Certificate',
    projects: '3 advanced C++ projects',
    topics: [
      'Introduction to C++',
      'Data Types and Operators',
      'Control Flow and Loops',
      'Object-Oriented Programming',
      'Inheritance and Polymorphism',
      'Exception Handling',
      'Templates and Generic Programming',
      'Standard Template Library (STL)',
      'File I/O in C++',
      'Building Applications with C++',
    ],
    image: cc,
  },
  'iot': {
    title: 'IoT Development',
    description: 'Build IoT solutions by connecting devices and sensors to the cloud.',
    duration: '5 months',
    cost: '$500',
    classes: 'Weekends (Sat & Sun)',
    certification: 'IoT Specialist Certification',
    projects: '3 IoT-based projects',
    topics: [
      'Introduction to IoT',
      'IoT Hardware: Sensors and Actuators',
      'Microcontrollers (Arduino and Raspberry Pi)',
      'IoT Protocols (MQTT, CoAP)',
      'Data Storage and Processing in the Cloud',
      'IoT Security',
      'Building Smart Home Systems',
    ],
    image: iot, // Replace `iotImg` with the appropriate image file
  },
  'javascript': {
    title: 'JavaScript Fundamentals',
    description: 'Learn JavaScript to create dynamic, interactive websites.',
    duration: '2 months',
    cost: '$150',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'JavaScript Developer Certificate',
    projects: '4 interactive web projects',
    topics: [
      'Introduction to JavaScript',
      'Variables and Data Types',
      'Functions and Scope',
      'DOM Manipulation',
      'Event Handling',
      'Asynchronous JavaScript (Promises and Async/Await)',
      'Working with APIs',
      'JavaScript Modules',
      'ES6+ Features',
      'Building Dynamic Websites',
    ],
    image: webdev,
  },
  'react': {
    title: 'React.js Development',
    description: 'Learn to build user interfaces using React.js.',
    duration: '3 months',
    cost: '$250',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'React Developer Certificate',
    projects: '5 React.js projects',
    topics: [
      'Introduction to React.js',
      'JSX and Components',
      'Props and State Management',
      'React Hooks',
      'Routing with React Router',
      'Working with Context API',
      'Building Forms in React',
      'Managing Side Effects',
      'React Performance Optimization',
      'Deploying React Applications',
    ],
    image: react,
  },
  'node': {
    title: 'Node.js Development',
    description: 'Learn backend development with Node.js and Express.js.',
    duration: '4 months',
    cost: '$300',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Node.js Developer Certificate',
    projects: '6 backend projects',
    topics: [
      'Introduction to Node.js',
      'Setting up Node.js Environment',
      'Understanding Modules and NPM',
      'Building REST APIs with Express.js',
      'Middleware and Routing',
      'Connecting to Databases (MongoDB, SQL)',
      'Authentication and Authorization',
      'Error Handling in Node.js',
      'Real-time Applications with WebSocket',
      'Deploying Node.js Applications',
    ],
    image: node,
  },
  'django': {
    title: 'Django Framework',
    description: 'Master backend development using Python’s Django framework.',
    duration: '3 months',
    cost: '$250',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Django Developer Certificate',
    projects: '5 Django web projects',
    topics: [
      'Introduction to Django',
      'Setting up Django Environment',
      'Creating and Managing Models',
      'Building Views and Templates',
      'Form Handling and Validation',
      'Authentication and Authorization',
      'Integrating APIs with Django',
      'Django ORM and Querysets',
      'Deploying Django Applications',
      'Building Scalable Web Apps with Django',
    ],
    image: django,
  },
  'flutter': {
    title: 'Flutter App Development',
    description: 'Learn to build cross-platform mobile apps with Flutter.',
    duration: '4 months',
    cost: '$300',
    classes: 'Weekdays (Mon to Fri)',
    certification: 'Flutter Developer Certificate',
    projects: '4 mobile app projects',
    topics: [
      'Introduction to Flutter',
      'Setting up Flutter Environment',
      'Building UI with Widgets',
      'State Management Techniques',
      'Navigation and Routing',
      'Integrating APIs and Databases',
      'Working with Firebase',
      'Handling Forms and Validations',
      'Publishing Apps on Play Store/App Store',
      'Best Practices in Flutter Development',
    ],
    image: flut,
  },
};

export default courseDetails;
